name: create-repository
on:
  workflow_dispatch:
    inputs: 
      prefix:  # 정해진 프리픽스만을 사용해야하니까 type : choice 
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
        - example
        - service
      name: #이름을 설정해야하는 곳 
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps: 
    - name: gh auth login #github 권한 받아오기 
      run: |
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
    - name: create-repo #입력받은 인풋값으로 repo 커맨드 작성 
      id: create-repo 
      run: |
        gh repo create jioh-practice/${{ inputs.prefix }}-${{inputs.name }} --public --add-readme
    - name: slack 
      if: always()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "attachments": [
              {
                "pretext": "create repo result",
                "color": "28a745",
                "fields": [
                  {
                    "title": "create repo result ${{ steps.create-repo.outcome }}",
                    "short": true,
                    "value": "${{ inputs.prefix }}-${{ inputs.name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK