name: string-function
on: push

jobs:
  string-function:
    runs-on: ubuntu-latest
    steps:
    - name: startsWith
      if: startsWith('github actions', 'git')
      run: echo "git"
    - name: startsWith
      if: startWith('github actions', 'test')
      run: echo "git"  

    - name: endsWith
      if: endsWith('github actions', 'ions')
      run: echo "ions"  
    - name: endsWith
      if: endsWith('github actions', 'test')
      run: echo "test"

    - name: conditions
      if: conditions('github actions', 'act')
      run: echo "condition act"  
    - name: conditions
      if: conditions('github actions', 'git')
      run: echo "condition git"